### ISSUE TITLE
Compile error luabind (git head 2016-01-18)

### ISSUE THREAD

**Issue by susnux** [ValyriaTear/ValyriaTear#522]
When building ValyriaTear with boost 1.60 and lua5.3 I get this error:

    [  139s] [ 17%] Built target translations
    [  165s] In file included from /home/abuild/rpmbuild/BUILD/ValyriaTear-1.0.0+20160118/src/luabind/luabind/back_reference.hpp:26:0,
    [  165s]                  from /home/abuild/rpmbuild/BUILD/ValyriaTear-1.0.0+20160118/src/luabind/luabind/class.hpp:72,
    [  165s]                  from /home/abuild/rpmbuild/BUILD/ValyriaTear-1.0.0+20160118/src/luabind/luabind/luabind.hpp:27,
    [  165s]                  from /home/abuild/rpmbuild/BUILD/ValyriaTear-1.0.0+20160118/src/utils/utils_pch.h:124:
    [  165s] /home/abuild/rpmbuild/BUILD/ValyriaTear-1.0.0+20160118/src/luabind/luabind/detail/has_get_pointer.hpp:98:22: error: 'mpl' in namespace 'boost' does not name a type
    [  165s]        typedef boost::mpl::bool_&lt;value&gt; type;
    [  165s]                       ^
    [  176s] src/CMakeFiles/valyriatear.dir/build.make:64: recipe for target '../src/utils/utils_pch.h.gch' failed
    [  176s] make[2]: *** [../src/utils/utils_pch.h.gch] Error 1
    [  176s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/ValyriaTear-1.0.0+20160118/build'
    [  176s] CMakeFiles/Makefile2:153: recipe for target 'src/CMakeFiles/valyriatear.dir/all' failed
    [  176s] make[1]: *** [src/CMakeFiles/valyriatear.dir/all] Error 2
    [  176s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/ValyriaTear-1.0.0+20160118/build'
    [  176s] Makefile:152: recipe for target 'all' failed
    [  176s] make: *** [all] Error 2

**Comment by Bertram25** [comment]
Hi @susnux :)

Thanks for the report about this. Unfortunately, I still don't have boost60 here so it will have to wait a bit more before I can try to reproduce. That said, mpl is a pretty common boost component, so hopefully, this can be solved rather easily. :)

**Comment by susnux** [comment]
I found a solution which works at least for me:
I replaced the luabind submodule with this one:
https://github.com/rpavlik/luabind

and modified the src/CMakeLists.txt for it.

**Comment by Bertram25** [comment]
Hi @susnux :)

I've upgraded the luabind version used with Valyria Tear. It seems the following commit could help:
https://github.com/ValyriaTear/luabind/commit/fb3c6623c728209a2ba69d178bd87589bf04e9cf

Feel free to tell whether it improves the situation or not.

As soon as I have libboost 1.58 at hand, I'll try to reproduce this issue.

Cheers.

**Comment by hasufell** [comment]
Doesn't build with boost-1.60 either:
```
[  1%] Building CXX object src/CMakeFiles/valyriatear.dir/common/global/global.cpp.o
cd /home/jule/git/ValyriaTear/build/src && /usr/host/bin/clang++    -I/usr/host/include -I/home/jule/git/ValyriaTear/src -I/usr/host/include/SDL2 -I/usr/host/include/AL -I/usr/host/include/lua5.1 -I/home/jule/git/ValyriaTear/src/luabind  -Wall -Wextra -std=c++11 -O3 -DNDEBUG   -DPACKAGE_VERSION=\"0.1.0\" -DPKG_DATADIR=\"/usr/local/share/valyriatear/\" -DLOCALEDIR=\"/usr/local/share/locale/\" -DPKG_NAME=\"valyriatear/\" -DUSE_X11 -DLUABIND_USE_CXX11 -o CMakeFiles/valyriatear.dir/common/global/global.cpp.o -c /home/jule/git/ValyriaTear/src/common/global/global.cpp
In file included from /home/jule/git/ValyriaTear/src/common/global/global.cpp:18:
In file included from /home/jule/git/ValyriaTear/src/utils/utils_pch.h:124:
In file included from /home/jule/git/ValyriaTear/src/luabind/luabind/luabind.hpp:27:
In file included from /home/jule/git/ValyriaTear/src/luabind/luabind/class.hpp:72:
In file included from /home/jule/git/ValyriaTear/src/luabind/luabind/back_reference.hpp:26:
/home/jule/git/ValyriaTear/src/luabind/luabind/detail/has_get_pointer.hpp:98:15: error: 
      no member named 'mpl' in namespace 'boost'; did you mean 'impl'?
      typedef boost::mpl::bool_<value> type;
              ^~~~~~~~~~
              impl
/home/jule/git/ValyriaTear/src/luabind/luabind/detail/has_get_pointer.hpp:90:10: note: 
      'impl' declared here
  struct impl
         ^
/home/jule/git/ValyriaTear/src/luabind/luabind/detail/has_get_pointer.hpp:98:27: error: 
      no type named 'bool_' in 'impl<T>'
      typedef boost::mpl::bool_<value> type;
              ~~~~~~~~~~~~^
/home/jule/git/ValyriaTear/src/luabind/luabind/detail/has_get_pointer.hpp:98:32: error: 
      expected member name or ';' after declaration specifiers
      typedef boost::mpl::bool_<value> type;
      ~~~~~~~~~~~~~~~~~~~~~~~~~^
```

**Comment by Bertram25** [comment]
Arf, I'll hint upstream right now.

**Comment by Bertram25** [comment]
@susnux @hasufell This one should now be fixed with: 45cd9fb2e33b5da27a031c3bb5713e607f97dc43

Don't forget to do: `git submodule update --remote` before trying again. Could verify for me?

Cheers. :)

**Comment by hasufell** [comment]
I have all sorts of problems now. It seems you have force-pushed.

**Comment by Bertram25** [comment]
> I have all sorts of problems now. It seems you have force-pushed.

If you're speaking about vt-luabind, I'm indeed guilty, but I did this because I want my own commits to stay clearly on top compared to @Oberon00 's repo.
I'll have to improve them so they get integrated once, though.

**Comment by hasufell** [comment]
You should never force-push to a repository that is used by others and not just for PR-work. You can have a cleaned-up secondary branch that you can use for your actual PR then.

**Comment by hasufell** [comment]
And yes, it compiles now.

**Comment by Bertram25** [comment]
> You should never force-push to a repository that is used by others and not just for PR-work. You can have a cleaned-up secondary branch that you can use for your actual PR then.

I'm well aware of the practice, but well, it's not as if VT was being worked by a full team of developers every day.

Cheers,

**Comment by Bertram25** [comment]
Closed with https://github.com/ValyriaTear/luabind/commit/45cd9fb2e33b5da27a031c3bb5713e607f97dc43
